spacenav node changed for ros2
ros-drivers/joystick_drivers pull request #194
Opened 2021-01-27 19:09 UTC by Schnilz

I updated the spacenav node to work on ros2.
I'm by no means a cmake expert, but it compiles and works on both of my linux machines.
I also changed the name of the package as no other node has the `_node` postfix. As this package is not on index.ros i hope thats an ok change.

2021-01-31 13:37 UTC, martimorta commented
Hi, 
I was going to take on this and seen you have done it already, thanks!
It works for me too in Ubuntu 20.04 with a space mouse compact.
Just a couple of things, I had to apt install libspnav-dev to compile and spacenavd to overcome the "use with sudo" error.
Cheers

2021-02-16 21:57 UTC, clalancette requested changes
First of all, thanks for the contribution.  This is a great addition to the package.

Second, I think it is fine to rename the package to `spacenav`.  As you say, it is more consistent with the other packages in this repository.

Third, I left a bunch of suggestions for improvement inline.  None of them are actually major; I think it would be a couple of hours to fix them up.  Once those fixes are done, I'll do another review pass.

2021-02-16 21:57 UTC, clalancette commented on spacenav/CMakeLists.txt
> +find_package(sensor_msgs REQUIRED)
Alphabetize the list, please.

2021-02-16 21:57 UTC, clalancette commented on spacenav/CMakeLists.txt
> +  "spnav")
Since `spnav` isn't an ament package, we should take it out of this list and instead use:

```
target_link_libraries(spacenav spnav::spnav)
```

or something like that.

2021-02-16 21:57 UTC, clalancette commented on spacenav/CMakeLists.txt
> +endif()
This should be removed in ROS 2 in favor of:

```
if(BUILD_TESTING)
  find_package(ament_lint_auto REQUIRED)
  set(ament_cmake_copyright_FOUND TRUE)
  ament_lint_auto_find_test_dependencies()
endif()
```

2021-02-16 21:57 UTC, clalancette commented on spacenav/README.md
> +* `spacenav/offset` (geometry_msgs/Vector3)
While `geometry_msgs/Vector3` still works in ROS 2, we prefer to use `geometry_msgs/msg/Vector3` (to distinguish from services and actions).  Same goes for all of the types below.

2021-02-16 21:57 UTC, clalancette commented on spacenav/README.md
> +$ros2 run spacenav spacenav
```suggestion
$ ros2 run spacenav spacenav
```

2021-02-16 21:57 UTC, clalancette commented on spacenav/cmake/Findspnav.cmake
> +ENDIF(UNIX)
Use consistent indent, switch all of the CMake statements to lower-case, and put a newline at the end of the file.

2021-02-16 21:57 UTC, clalancette commented on spacenav/launch/classic.launch.py
> +from launch import LaunchDescription
We've been preferring to call these files `classic-launch.py`.  Also add a newline at the end of the file.  Same goes for all of the launch files below.

2021-02-16 21:57 UTC, clalancette commented on spacenav/package.xml
> +  <version>1.0.0</version>
The version number has to match all of the other packages in the repository.  In this case, please set it to 2.4.1.

2021-02-16 21:57 UTC, clalancette commented on spacenav/package.xml
>    <depend>sensor_msgs</depend>
Alphabetize this list please.

2021-02-16 21:57 UTC, clalancette commented on spacenav/package.xml
> +
Add in:

```
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
```

2021-02-16 21:57 UTC, clalancette commented on spacenav/src/spacenav.cpp
> +    timer_ = this->create_wall_timer(1000us,
```suggestion
    timer_ = this->create_wall_timer(1ms,
```

2021-02-16 21:57 UTC, clalancette commented on spacenav/src/spacenav.cpp
> +}
As-is, this implementation is actually pretty close to be composable.  If you put the definition of the class into a header file (in `include/spacenav`), leave the implementation of the class in this file and add `RCLCPP_COMPONENTS_REGISTER_NODE(spacenav::Spacenav)` at the end, and remove the whole `main`, it will be composable (see the https://github.com/ros-drivers/joystick_drivers/blob/ros2/joy/src/joy.cpp , https://github.com/ros-drivers/joystick_drivers/blob/ros2/joy/include/joy/joy.hpp , and https://github.com/ros-drivers/joystick_drivers/blob/ros2/joy/CMakeLists.txt#L37 for an example on how to do this).

2021-02-16 21:57 UTC, clalancette commented on spacenav/src/spacenav.cpp
> +
It's good practice to make all of the code in a module in a namespace.  I'll suggest `spacenav` here to match the name of the package.

2021-02-24 17:59 UTC, Schnilz commented
thanks for the review!

I applied all your suggenstions and  used my editors auto code formatter for formatting, i hope thats ok :)

2021-02-24 18:45 UTC, clalancette requested changes
OK, I did a bunch of additional cleanup in here.  This is pretty close.

One thing that is missing is a copyright statement in the new files.  In particular, CI won't pass until there is a copyright statement in the `spacenav.hpp` file, but we should also add a copyright to the launch files as well.  Once that is done, CI should pass and I think this will be ready to go in.

2021-02-24 18:45 UTC, clalancette commented on spacenav/package.xml
> +  <buildtool_depend>ament_cmake_ros</buildtool_depend>
```suggestion
  <buildtool_depend>ament_cmake</buildtool_depend>
```

2021-02-24 21:28 UTC, clalancette commented
All right, this is passing the Foxy and Rolling PR jobs.  The "Basic Build Workflow" is broken for reasons totally unrelated to this PR, so I'm going to go ahead and merge.  Thanks @Schnilz for the contribution!

2021-02-24 21:28 UTC, merged