Upgrade to SDL2.0.18
ros-drivers/joystick_drivers pull request #270
Opened 2023-10-05 14:25 UTC by roncapat

Fix #267

2023-10-10 17:39 UTC, clalancette requested changes

2023-10-10 17:39 UTC, clalancette commented on sdl2_vendor/CMakeLists.txt
> +  ExternalProject_Add(SDL2-2.0.18
If we are going to update it, I'd rather we update to 2.0.20, as that is the version that is shipped in Ubuntu 22.04.  Do you mind doing that?

2023-10-10 17:40 UTC, roncapat commented on sdl2_vendor/CMakeLists.txt
> +  ExternalProject_Add(SDL2-2.0.18
Ah yes, of course :)

2023-10-12 15:38 UTC, roncapat commented
@clalancette I noticed a problem with the `sdl2_vendor/sdl2-windows-add-vcruntime.patch` patch not being applied. I'll do some checks and report.

2023-10-12 16:00 UTC, roncapat commented
Should be fixed now. I warn you that it seems to me that during CI the SDL doesn't get built from sources (it may already be present in Ubuntu packages). Maybe `FORCE_BUILD_VENDOR_PKG` is not set?

2023-10-12 20:49 UTC, clalancette commented
> Maybe `FORCE_BUILD_VENDOR_PKG` is not set?

Yeah, it is not: https://github.com/ros-drivers/joystick_drivers/blob/ros2/.github/workflows/rolling-build-ci.yaml

The vendoring of this package was mostly meant for Windows; on Linux, we generally have a packaged SDL available (though I guess in this case, it might be too old).  One thing we could consider would be to build it if the SDL version is not new enough to have the game controller interface.

2023-10-12 21:24 UTC, clalancette approved these changes
Looks good to me, thanks for the update.

2023-10-12 21:25 UTC, merged